### ISSUE TITLE
Can we put everything in a subfolder called client or unity

### ISSUE THREAD

**Issue by TheNotary** [TriNetCo/NetGrid#2]
Once I get more the hang of working with Unity, I'd like to add the database API to this repo, and perhaps an html GUI for "Sign Up Free."

**Comment by Macklehatton** [comment]
The top folder name for the project (the folder that contains 'Assets') should be the same as the Unity project name by convention. Not sure if it's bad to have that also match the GitHub repo name?

- It isn't an issue to move the project folder around
- It's possible to keep all the paths relative
- Having things beside it won't be a problem
- Usually you can put whatever you want in the top level project folder as well

Other stuff about folders

- Plugins is a magic folder for libraries and dlls that don't support the newish package manager
- - They'll won't be rebuilt when the project is rebuilt
- Editor folders are magic too, they're for things that modify the Unity editor itself
- You might see references to a Resources folder, but this can (and probably should) be avoided

**Comment by TheNotary** [comment]
I just created #4 which is an implementation of this proposal (plus a scratch CS file that was sitting around).  What do you think?
